[package]
name = "zipherx-ffi"
version.workspace = true
edition.workspace = true

[lib]
name = "zipherx_ffi"
crate-type = ["staticlib", "cdylib"]

[dependencies]
zipherx-core = { workspace = true }
zipherx-crypto = { workspace = true }
zipherx-network = { workspace = true }
zipherx-storage = { workspace = true }
zipherx-tor = { path = "../zipherx-tor" }
zipherx-platform = { workspace = true }
uniffi = { version = "0.28", features = ["cli"] }
tokio.workspace = true
tracing.workspace = true
thiserror.workspace = true
hex.workspace = true
serde.workspace = true
serde_json.workspace = true

[build-dependencies]
uniffi = { version = "0.28", features = ["build"] }
